In [1]:
from numpy import random
print(random.randint(100))

28


In [2]:
print(random.rand())

0.3701867559290076


In [9]:
print(random.randint(100,size=(3,5,4)))

[[[80  8 39 82]
  [49 13 34 75]
  [15 62 48 83]
  [72 23 65 50]
  [38 45 22 31]]

 [[71  6 59 99]
  [ 1 55 42 70]
  [83 71 77 67]
  [45 26 54 64]
  [20 56 85 94]]

 [[60 33 48 14]
  [68 65  1 35]
  [31 52 39 69]
  [99 42 78 81]
  [42 62 61 74]]]


In [6]:
print(random.randint(100,size=(2)))

[60 10]


In [8]:
print(random.choice([1,2,3,4,5]))

5


In [10]:
import numpy as np

In [30]:
a1=np.arange(1,10).reshape(3,3)
print(a1)
print(a1.ravel())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [25]:
a2=np.arange(1,20)
print(random.choice(a2))

14


In [32]:
x=random.choice([1,2,3,4,5],size=(3,4))
print(x)

[[3 2 5 2]
 [1 3 3 3]
 [2 2 4 5]]


In [37]:
random.shuffle(a2)
print(a2)

[ 6 12 11  9  8 15 19  4 17  3  7 16 13  1 14  5 18 10  2]


## Pandas:
1. Data manipulations, Analysis and Cleaning
2. Tabular, Unlabelled

### Creating a dataframe
1. using 2 dictionaries
2. simple dictionary
3. using series

In [43]:
import pandas as pd
import numpy as np
dict1={'a':1,'b':2,'c':3,'d':4,'e':5}
dict2={'a':6,'b':7,'c':8,'d':9,'e':10}
data={"First":dict1,"Second":dict2}
df=pd.DataFrame(data)
df#NaN which stands for not a number

First  Second
a      1       6
b      2       7
c      3       8
d      4       9
e      5      10

In [44]:
#using simple dictionary
d1={"name":["Rohith","Sai","xyz"],"address":["hyd","bho","pat"]}
df1=pd.DataFrame(d1)
df1

name address
0  Rohith     hyd
1     Sai     bho
2     xyz     pat

In [47]:
#using series
s1=pd.Series([1,2,3,4,5,6,7,8,9,10])
s2=pd.Series([11.2,12.2,12.34,54.3,23.21,21.4,145.32,12.4,94,23])
s3=pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data={"column1":s1,"column2":s2,"Column3":s3}
df3=pd.DataFrame(data)
df3

column1  column2 Column3
0        1    11.20       a
1        2    12.20       b
2        3    12.34       c
3        4    54.30       d
4        5    23.21       e
5        6    21.40       f
6        7   145.32       g
7        8    12.40       h
8        9    94.00       i
9       10    23.00       j

In [48]:
#extracting columns from dataframe
df3[["column1","column2"]]

column1  column2
0        1    11.20
1        2    12.20
2        3    12.34
3        4    54.30
4        5    23.21
5        6    21.40
6        7   145.32
7        8    12.40
8        9    94.00
9       10    23.00

### Selecting the data from the DataFrame
1. loc
2. iloc

In [49]:
#single column
df3.loc[:,"column1"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [54]:
#loc[row index,column]
df3.loc[0:5,["column1","column2"]]

column1  column2
0        1    11.20
1        2    12.20
2        3    12.34
3        4    54.30
4        5    23.21
5        6    21.40

In [55]:
type(df3)

pandas.core.frame.DataFrame

In [58]:
df3.iloc[:,1]

0     11.20
1     12.20
2     12.34
3     54.30
4     23.21
5     21.40
6    145.32
7     12.40
8     94.00
9     23.00
Name: column2, dtype: float64

In [60]:
#iloc[row index,column index]
df3.iloc[0:4,0:2]

column1  column2
0        1    11.20
1        2    12.20
2        3    12.34
3        4    54.30

### Retrieving the information of DataFrame


In [61]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   column1  10 non-null     int64  
 1   column2  10 non-null     float64
 2   Column3  10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [62]:
df3.columns

Index(['column1', 'column2', 'Column3'], dtype='object')

In [63]:
df3.index

RangeIndex(start=0, stop=10, step=1)

In [64]:
df3.shape

(10, 3)

## Viewing data from DataFrame:
1. head()
2. tail()
3. sample()

In [65]:
df3.head()

column1  column2 Column3
0        1    11.20       a
1        2    12.20       b
2        3    12.34       c
3        4    54.30       d
4        5    23.21       e

In [69]:
df3.tail()

column1  column2 Column3
5        6    21.40       f
6        7   145.32       g
7        8    12.40       h
8        9    94.00       i
9       10    23.00       j

In [67]:
df3.sample()

column1  column2 Column3
2        3    12.34       c

In [70]:
df3.head(3)

column1  column2 Column3
0        1    11.20       a
1        2    12.20       b
2        3    12.34       c

In [71]:
#gives all the statistics for numerical data
df3.describe()

column1     column2
count  10.00000   10.000000
mean    5.50000   40.937000
std     3.02765   45.030844
min     1.00000   11.200000
25%     3.25000   12.355000
50%     5.50000   22.200000
75%     7.75000   46.527500
max    10.00000  145.320000

In [74]:
df3=df3.rename(columns={"column1":"First",
                    "column2":"Second",
                    "column3":"Third"})
df3

First  Second Column3
0      1   11.20       a
1      2   12.20       b
2      3   12.34       c
3      4   54.30       d
4      5   23.21       e
5      6   21.40       f
6      7  145.32       g
7      8   12.40       h
8      9   94.00       i
9     10   23.00       j