In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import sklearn as sc

In [2]:
# import the dataset
#data=pd.read_table("http://bit.ly/movieusers")
#data

In [3]:
#data=pd.read_table("http://bit.ly/movieusers",sep="|",header=None)
#data.head(2)


## Handling the missing values

In [4]:
df=pd.read_csv("https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/weather_data.csv")
df

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [5]:
# returns the frequency of column values
df['temperature'].value_counts()

-99999    2
 32       2
 31       1
 28       1
 34       1
Name: temperature, dtype: int64

In [6]:
df['day'].dtype

dtype('O')

In [7]:
type(df.day[0])

str

In [8]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [9]:
df['temperature'].duplicated()

0    False
1    False
2    False
3     True
4     True
5    False
6    False
Name: temperature, dtype: bool

In [10]:
df[df['temperature'].duplicated()]

day  temperature  windspeed event
3  1/4/2017       -99999          7     0
4  1/5/2017           32     -99999  Rain

In [11]:
df[df['event'].duplicated()]

day  temperature  windspeed  event
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [12]:
df['event'].value_counts()

Rain     2
Sunny    2
0        2
Snow     1
Name: event, dtype: int64

In [3]:
df1=pd.read_csv("https://raw.githubusercontent.com/Mounika-Kajjam/Datasets/master/weather_data.csv",parse_dates=['day'])
df1

day  temperature  windspeed  event
0 2017-01-01           32          6   Rain
1 2017-01-02       -99999          7  Sunny
2 2017-01-03           28     -99999   Snow
3 2017-01-04       -99999          7      0
4 2017-01-05           32     -99999   Rain
5 2017-01-06           31          2  Sunny
6 2017-01-06           34          5      0

In [14]:
df1.day.dtype

dtype('<M8[ns]')

In [16]:
type(df1.day[0])

pandas._libs.tslibs.timestamps.Timestamp

In [4]:
new_df=df1.replace({'temperature':-99999,'windspeed':-99999,'event':'0'},np.nan)
new_df

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02          NaN        7.0  Sunny
2 2017-01-03         28.0        NaN   Snow
3 2017-01-04          NaN        7.0    NaN
4 2017-01-05         32.0        NaN   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0    NaN

## imputation: it is a process of substituting the missing values

In [20]:
new_df.isnull().sum()

day            0
temperature    2
windspeed      2
event          2
dtype: int64

In [37]:
## fillna() is a fuction which is used to fill the missing values
df1=new_df.fillna(0)
df1

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02          0.0        7.0  Sunny
2 2017-01-03         28.0        0.0   Snow
3 2017-01-04          0.0        7.0      0
4 2017-01-05         32.0        0.0   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0      0

In [43]:
new_df.fillna(method='ffill')
new_df

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02         32.0        7.0  Sunny
2 2017-01-03         28.0        7.0   Snow
3 2017-01-04         28.0        7.0   Snow
4 2017-01-05         32.0        7.0   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0  Sunny

In [44]:
f_data=new_df.fillna(method='ffill')
f_data

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02         32.0        7.0  Sunny
2 2017-01-03         28.0        7.0   Snow
3 2017-01-04         28.0        7.0   Snow
4 2017-01-05         32.0        7.0   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0  Sunny

In [6]:
b_data=new_df.fillna(method='bfill')
b_data

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02         28.0        7.0  Sunny
2 2017-01-03         28.0        7.0   Snow
3 2017-01-04         32.0        7.0   Rain
4 2017-01-05         32.0        2.0   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0    NaN

In [7]:
new_df

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02          NaN        7.0  Sunny
2 2017-01-03         28.0        NaN   Snow
3 2017-01-04          NaN        7.0    NaN
4 2017-01-05         32.0        NaN   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0    NaN

In [9]:
mean_data=new_df.fillna(new_df.mean())
mean_data

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02         31.4        7.0  Sunny
2 2017-01-03         28.0        5.4   Snow
3 2017-01-04         31.4        7.0    NaN
4 2017-01-05         32.0        5.4   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0    NaN

In [10]:
## median imputation
median_data=new_df.fillna(new_df.median())
median_data

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02         32.0        7.0  Sunny
2 2017-01-03         28.0        6.0   Snow
3 2017-01-04         32.0        7.0    NaN
4 2017-01-05         32.0        6.0   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0    NaN

In [16]:
new_df['event']=new_df['event'].fillna(new_df.event.mode().iloc[0])

In [17]:
new_df

day  temperature  windspeed  event
0 2017-01-01         32.0        6.0   Rain
1 2017-01-02          NaN        7.0  Sunny
2 2017-01-03         28.0        NaN   Snow
3 2017-01-04          NaN        7.0   Rain
4 2017-01-05         32.0        NaN   Rain
5 2017-01-06         31.0        2.0  Sunny
6 2017-01-06         34.0        5.0   Rain

In [19]:
event_data=new_df['event'].fillna(new_df.event.mode().iloc[0])
print(event_data)

0     Rain
1    Sunny
2     Snow
3     Rain
4     Rain
5    Sunny
6     Rain
Name: event, dtype: object


In [22]:
import numpy as np
arr1 = np.array([[10,5,20,0],
                 [1,19,2,13],
                 [3,12,2,18],
                 [21,-1,11,4]])

In [23]:
arr1

array([[10,  5, 20,  0],
       [ 1, 19,  2, 13],
       [ 3, 12,  2, 18],
       [21, -1, 11,  4]])

In [24]:
arr1.sum(axis=1)

array([35, 35, 35, 35])

In [26]:
arr1.trace(axis1=1,axis2=0)

35

In [37]:
s=0
for i in range(1,3):
    for j in range(1,3):
        s+=arr1[i,j]
print(s)

35


In [38]:
np.diagflat([1,2], -1)

array([[0, 0, 0],
       [1, 0, 0],
       [0, 2, 0]])

In [39]:
np.tril([[1,211,3],[4,51,6],[7,18,9]], 0)

array([[ 1,  0,  0],
       [ 4, 51,  0],
       [ 7, 18,  9]])

In [40]:
word = "word"

print(word.__len__())

4


In [41]:
import numpy as np

arr = np.array([1,2,3,4,5])

np.percentile(arr,50)

3.0

7
